export const STR = {
  en: {
    title: 'Wishlist', intro: 'Keep your gift ideas together. Make a collection, add something special and share it when you’re ready.',
    collections: 'Collections', collectionName: 'Collection name', create: 'Create collection', rename: 'Rename', deleteCollection: 'Delete collection',
    confirmCollection: 'Delete this collection and all its products? This cannot be undone.', confirmItem: 'Delete this product?',
    emptyCollections: 'Your first wish starts here. Create a collection such as Birthday, Home or Books.',
    empty: 'No products yet. Add a product link to start this collection.', noMatch: 'No products match your filters.',
    add: 'Add product', edit: 'Edit', remove: 'Delete', url: 'Product URL (HTTPS)', fetch: 'Fetch details',
    metadataHint: 'Automatic details: Amazon and bol. Other shops can be entered manually. Always check the price and availability.',
    metadataBackend: 'Automatic product details are not available on the server yet. You can still enter and save the product manually.',
    metadataAuth: 'Your session has expired. Sign in again to fetch product details.',
    metadataRateLimit: 'Too many import requests. Wait a minute and try again.',
    metadataBlocked: 'The shop blocked automatic access. Open the product in the shop and enter its details manually.',
    metadataUnsupported: 'Automatic details are supported for Amazon and bol product pages. Enter other shops manually.',
    metadataWishlist: 'This is a whole wishlist. Importing external wishlists is not supported yet. Open the list and paste an individual product link.',
    metadataFailed: 'Could not fetch details. Check the link and fill in the fields manually.', metadataDone: 'Details retrieved. Review them before saving.',
    productTitle: 'Product name', price: 'Price (optional)', currency: 'Currency', tags: 'Tags (comma-separated)', priority: 'Priority',
    availability: 'Availability', unknown: 'Unknown', in_stock: 'In stock', out_of_stock: 'Out of stock', preorder: 'Preorder',
    high: 'High', normal: 'Normal', low: 'Low', save: 'Save product', cancel: 'Cancel', saved: 'Saved.',
    invalid: 'Check the URL, name, price, three-letter currency and tags (up to 20, 30 characters each).', duplicate: 'This product is already in this collection. Edit the existing item to update its details.',
    failed: 'Something went wrong. Try again. If this persists, check that the Wishlist database migration has been applied.',
    loading: 'Loading…', working: 'Working…', retry: 'Retry', search: 'Search products', tagFilter: 'Filter by tag', allTags: 'All tags',
    sort: 'Sort by', date: 'Date added', store: 'Shop', priceSort: 'Price (low to high, grouped by currency)',
    share: 'Create share link', private: 'Private', shared: 'Anyone with the link', stopShare: 'Disable link',
    rotate: 'Replace link', confirmRotate: 'Replace the link? The old link will stop working.', copy: 'Copy link', copied: 'Link copied.', copyFailed: 'Copy failed. Select and copy the link below.',
    shareHint: 'Everyone with this link can view and reserve gifts. Reservations are hidden from your account. Disabling a link keeps existing reservations.',
    sharedTitle: 'A little inspiration', sharedIntro: 'Choose a gift and reserve it to avoid doubles. No account needed.',
    unavailable: 'This link is invalid, disabled or the collection no longer exists.', owner: 'This is your collection. Open your Wishlist to manage it; reservations stay hidden here.',
    manage: 'My Wishlist', reserve: 'Reserve gift', reserved: 'Reserved', cancelReservation: 'Cancel my reservation',
    reservedDone: 'Gift reserved. Keep this browser to cancel your reservation later.', conflict: 'This gift was already reserved. The list has been refreshed.',
    cancelled: 'Reservation cancelled.', storageFailed: 'Allow browser storage to reserve a gift and keep its cancellation key.',
    reservationHint: 'Cancellation is available in this browser. Clearing browser data loses that option. Prices and availability are indicative; check the shop before buying.',
    refresh: 'Refresh list', open: 'View in shop', preferencesError: 'Your display preferences could not be saved or loaded.',
  },
  nl: {
    title: 'Verlanglijstjes', intro: 'Bewaar je cadeau-ideeën bij elkaar. Maak een collectie, voeg iets bijzonders toe en deel ze wanneer je wilt.',
    collections: 'Collecties', collectionName: 'Naam van de collectie', create: 'Collectie maken', rename: 'Hernoemen', deleteCollection: 'Collectie verwijderen',
    confirmCollection: 'Deze collectie en alle producten verwijderen? Dit kan niet ongedaan worden gemaakt.', confirmItem: 'Dit product verwijderen?',
    emptyCollections: 'Je eerste wens begint hier. Maak een collectie zoals Verjaardag, Huis of Boeken.',
    empty: 'Nog geen producten. Voeg een productlink toe om deze collectie te beginnen.', noMatch: 'Geen producten gevonden met deze filters.',
    add: 'Product toevoegen', edit: 'Bewerken', remove: 'Verwijderen', url: 'Product-URL (HTTPS)', fetch: 'Gegevens ophalen',
    metadataHint: 'Automatische gegevens: Amazon en bol. Andere winkels kun je handmatig invoeren. Controleer altijd de prijs en beschikbaarheid.',
    metadataBackend: 'Automatische productgegevens zijn nog niet beschikbaar op de server. Je kunt het product wel handmatig invoeren en opslaan.',
    metadataAuth: 'Je sessie is verlopen. Meld je opnieuw aan om productgegevens op te halen.',
    metadataRateLimit: 'Te veel importverzoeken. Wacht een minuut en probeer opnieuw.',
    metadataBlocked: 'De winkel blokkeert automatische toegang. Open het product bij de winkel en vul de gegevens handmatig in.',
    metadataUnsupported: 'Automatische gegevens werken voor productpagina’s van Amazon en bol. Voer andere winkels handmatig in.',
    metadataWishlist: 'Dit is een volledig verlanglijstje. Externe verlanglijstjes importeren wordt nog niet ondersteund. Open de lijst en plak de link naar een afzonderlijk product.',
    metadataFailed: 'Gegevens ophalen is niet gelukt. Controleer de link en vul de velden handmatig in.', metadataDone: 'Gegevens opgehaald. Controleer ze voordat je opslaat.',
    productTitle: 'Productnaam', price: 'Prijs (optioneel)', currency: 'Valuta', tags: 'Tags (gescheiden door komma’s)', priority: 'Prioriteit',
    availability: 'Beschikbaarheid', unknown: 'Onbekend', in_stock: 'Op voorraad', out_of_stock: 'Niet op voorraad', preorder: 'Voorbestelling',
    high: 'Hoog', normal: 'Normaal', low: 'Laag', save: 'Product opslaan', cancel: 'Annuleren', saved: 'Opgeslagen.',
    invalid: 'Controleer de URL, naam, prijs, valutacode van drie letters en tags (maximaal 20 van elk 30 tekens).', duplicate: 'Dit product staat al in deze collectie. Bewerk het bestaande product om de gegevens bij te werken.',
    failed: 'Er ging iets mis. Probeer opnieuw. Blijft dit gebeuren, controleer dan of de database-migratie voor Verlanglijstjes is uitgevoerd.',
    loading: 'Laden…', working: 'Bezig…', retry: 'Opnieuw proberen', search: 'Producten zoeken', tagFilter: 'Filteren op tag', allTags: 'Alle tags',
    sort: 'Sorteren op', date: 'Datum toegevoegd', store: 'Winkel', priceSort: 'Prijs (laag naar hoog, per valuta)',
    share: 'Deellink maken', private: 'Privé', shared: 'Iedereen met de link', stopShare: 'Link uitschakelen',
    rotate: 'Link vervangen', confirmRotate: 'De link vervangen? De oude link werkt daarna niet meer.', copy: 'Link kopiëren', copied: 'Link gekopieerd.', copyFailed: 'Kopiëren is niet gelukt. Selecteer en kopieer de link hieronder.',
    shareHint: 'Iedereen met deze link kan cadeaus bekijken en reserveren. Reserveringen zijn verborgen voor jouw account. Uitschakelen van een link behoudt bestaande reserveringen.',
    sharedTitle: 'Een beetje inspiratie', sharedIntro: 'Kies een cadeau en reserveer het om dubbele cadeaus te voorkomen. Geen account nodig.',
    unavailable: 'Deze link is ongeldig, uitgeschakeld of de collectie bestaat niet meer.', owner: 'Dit is jouw collectie. Open je Verlanglijstjes om ze te beheren; reserveringen blijven hier verborgen.',
    manage: 'Mijn verlanglijstjes', reserve: 'Cadeau reserveren', reserved: 'Gereserveerd', cancelReservation: 'Mijn reservering annuleren',
    reservedDone: 'Cadeau gereserveerd. Bewaar deze browser om je reservering later te annuleren.', conflict: 'Dit cadeau was al gereserveerd. De lijst is vernieuwd.',
    cancelled: 'Reservering geannuleerd.', storageFailed: 'Sta browseropslag toe om een cadeau te reserveren en de annuleringssleutel te bewaren.',
    reservationHint: 'Annuleren kan in deze browser. Als je browsergegevens wist, verlies je die mogelijkheid. Prijzen en voorraad zijn indicatief; controleer de winkel voor aankoop.',
    refresh: 'Lijst vernieuwen', open: 'Bekijken bij de winkel', preferencesError: 'Je weergavevoorkeuren konden niet worden opgeslagen of geladen.',
  },
}
