export const SPEECH_STR = {
  en: {
    hint: 'Hear the words, find the song, follow every line. Keep the microphone on to stay aligned with the singer.',
    language: 'Song language', start: 'Listen to the words', stop: 'Stop listening', resume: 'Resume listening',
    heard: 'Words heard', waiting: 'Waiting for a clear vocal phrase…', searching: 'Finding the song from these words…',
    following: 'Following the singer', aligning: 'Waiting for a distinctive phrase to align…', paused: 'Microphone paused',
    noMatch: 'No confident match yet. Keep listening for another phrase, or correct the words below.',
    unsupported: 'Speech recognition is unavailable in this browser. Use a browser with speech recognition or switch to Audio recognition.',
    permission: 'Allow microphone access in your browser, then try again.',
    network: 'The speech service is unavailable. Check your connection and try again.',
    failed: 'Speech recognition stopped. Try starting the microphone again.',
    silent: 'No words were detected. Try a clearer vocal section and start again.',
    lookupFailed: 'Lyrics lookup is unavailable right now. Try again shortly.',
    privacy: 'Your browser’s speech service may process microphone audio remotely. Detected phrases are sent to Toolbox and Unison to find full lyrics. Title/artist searches use LRCLIB. Both lyric services are free and need no API key.',
    manual: 'Find or correct the song', phrase: 'Heard words', title: 'Title / artist',
    placeholder: 'At least four words from the song…', titlePlaceholder: 'Song title or artist…',
    search: 'Find lyrics', results: 'Possible matches — choose the song you hear',
    another: 'Find another song', source: 'Lyrics from LRCLIB', tap: 'Tap a line to help alignment, especially during a repeated chorus.',
    noResults: 'No full lyrics found. Try another phrase or search by title and artist.',
  },
  nl: {
    hint: 'Hoor de woorden, vind het nummer en volg elke regel. Laat de microfoon aan om de zanger te blijven volgen.',
    language: 'Taal van het nummer', start: 'Luister naar de woorden', stop: 'Stop met luisteren', resume: 'Verder luisteren',
    heard: 'Gehoorde woorden', waiting: 'Wachten op een duidelijk gezongen zin…', searching: 'Het nummer zoeken met deze woorden…',
    following: 'De zanger volgen', aligning: 'Wachten op een onderscheidende zin om te synchroniseren…', paused: 'Microfoon gepauzeerd',
    noMatch: 'Nog geen zekere match. Luister verder of verbeter de woorden hieronder.',
    unsupported: 'Spraakherkenning is niet beschikbaar in deze browser. Gebruik een browser met spraakherkenning of schakel naar Audioherkenning.',
    permission: 'Sta microfoontoegang toe in je browser en probeer opnieuw.',
    network: 'De spraakdienst is niet beschikbaar. Controleer je verbinding en probeer opnieuw.',
    failed: 'Spraakherkenning is gestopt. Probeer de microfoon opnieuw te starten.',
    silent: 'Geen woorden gehoord. Probeer een duidelijker gezongen stuk en start opnieuw.',
    lookupFailed: 'Songteksten zoeken is tijdelijk niet beschikbaar. Probeer het straks opnieuw.',
    privacy: 'De spraakdienst van je browser kan microfoonaudio op afstand verwerken. Gehoorde zinnen worden naar Toolbox en Unison gestuurd om volledige teksten te vinden. Zoeken op titel/artiest gebruikt LRCLIB. Beide tekstdiensten zijn gratis en vereisen geen API-sleutel.',
    manual: 'Vind of verbeter het nummer', phrase: 'Gehoorde woorden', title: 'Titel / artiest',
    placeholder: 'Minstens vier woorden uit het nummer…', titlePlaceholder: 'Titel of artiest…',
    search: 'Zoek songtekst', results: 'Mogelijke matches — kies het nummer dat je hoort',
    another: 'Een ander nummer zoeken', source: 'Songtekst van LRCLIB', tap: 'Tik op een regel om te synchroniseren, vooral bij een herhaald refrein.',
    noResults: 'Geen volledige songtekst gevonden. Probeer een andere zin of zoek op titel en artiest.',
  },
}
