export const LEGAL_VERSION = '2026-10-09'
export const TERMS_VERSION = '2026-10-09.2'
export const PRIVACY_VERSION = '2026-10-09'
export const PRIVACY_CONTACT = 'privacy@zacsvae.com'
export const OPERATOR = 'Isaac Sauer'
export interface LegalSection { title: string; paragraphs: string[] }

export const privacySections: LegalSection[] = [
  { title: 'Who is responsible', paragraphs: [
    'Toolbox at toolbox.zacsvae.com is operated by Isaac Sauer in Belgium. Isaac Sauer is the controller of personal data processed to operate Toolbox. Contact privacy@zacsvae.com for privacy questions, rights requests, or complaints.',
    'This notice covers Toolbox accounts, saved settings and creations, shared links, and the tools provided through this website. External websites and services have their own privacy notices. Accounts are available only to people aged 18 or over.'
  ] },
  { title: 'What we collect and why', paragraphs: [
    'Account data includes your email address, account identifier, account creation details, authentication records, free/pro/master role, access settings, suspension status, and saved-data usage. Supabase handles your password and authentication; your login password is not stored in Toolbox application tables. We use account data to provide and secure your account.',
    'You choose what to save: tool settings, favourites, QR code content and designs, work-hour and meal-planning records, board-game scores, wishlist collections, product URLs, prices, tags, images, and other tool records. Certain tools can save locations or upstream API credentials as part of your settings. These values are included in your account export; treat that file as private. Only enter data needed for your task and avoid unnecessary sensitive information or other people’s personal data.',
    'When you use server tools, we process the files, images, video URLs, audio samples, captions, filenames, and options you submit. We associate new file-processing jobs and transfers with your account identifier so we can remove them when you delete your account. That identifier is not shown to shared-link recipients.',
    'Technical requests reveal information such as your IP address, browser headers, requested URL, and time to hosting/network providers. The backend also uses IP addresses for temporary abuse-prevention limits. Messages you send to the contact email are processed to answer you and handle requests.'
  ] },
  { title: 'Legal bases', paragraphs: [
    'For EEA and UK users, we process account, saved-content, and requested tool data to provide the service you request and perform our agreement with you. We rely on legitimate interests for proportionate security, abuse prevention, service maintenance, and handling ordinary support messages, taking account of your rights. We process information to meet legal obligations where necessary.',
    'The signup acknowledgement of this notice is not consent to advertising or an unrestricted waiver of privacy rights. Browser microphone and location permissions let you choose whether to use those optional features. Where applicable law requires consent for a particular optional processing operation, you may decline it and use other available tools. We do not use the account signup checkbox to authorize marketing.'
  ] },
  { title: 'Where processing happens and who receives data', paragraphs: [
    'GitHub Pages hosts the frontend, Cloudflare carries requests to the backend, and Supabase provides authentication and the application database. The operator administers the backend and account permissions. Authorized administration can access account details and stored application data for support, security, and service operation; access is not a promise that the operator can never view stored content.',
    'Image Toolbox, Video Editor, Meme Studio rendering, and local background removal process selected media in your browser. Background removal may download AI models and runtime files from jsDelivr, Google-hosted model storage, and Hugging Face; those providers receive the download request and connection details, rather than the media being processed locally.',
    'Other tools intentionally contact providers. Weather requests go to Open-Meteo and NOAA; mapping/solar requests may go to OpenStreetMap/Nominatim, Esri, Google/Apple Maps, the European Commission’s solar service, or public fetch proxies such as AllOrigins and Jina. Requested places, coordinates, or URLs may be sent to the relevant provider. Avoid putting private information in a URL you ask a proxy to fetch.',
    'Live Lyrics searches use LRCLIB and Unison. Audio recognition uploads a short microphone sample to the backend, which may send an audio fingerprint to Shazam through ShazamIO. Speech-to-lyrics uses your browser’s speech-recognition service, which may process audio remotely depending on your browser, and sends detected phrases for lyric search. Only activate these features when you are comfortable with that processing.',
    'Wishlist imports fetch the retailer URL you provide; product images load directly from their image hosts in your browser. Other tool-specific requests can reach yt-dlp-supported video websites, GitHub, meme-template/image hosts, public holiday providers, and, where enabled, stock/football/movie data services. Upstream API credentials are sent only to the relevant provider or the backend route that serves that provider. Toolbox does not sell personal data or use it for cross-context behavioural advertising.'
  ] },
  { title: 'Sharing and international processing', paragraphs: [
    'A shared wishlist link exposes its list name, product details, and whether items are reserved. Reservation cancellation tokens stay private to the guest who holds them. A file-transfer link exposes file metadata and enables access under the password/download-token settings you choose. Image results and subtitle links also act as access capabilities. Anyone who receives such a link may copy or redistribute its content; account deletion cannot erase copies already downloaded by someone else.',
    'Our providers operate internationally, so request data and some service data may be processed outside Belgium and the EEA, including in the United States. The exact Supabase project region and configured backup/log retention are being verified. Contact us for the current hosting details and applicable transfer safeguards. We cannot represent an unverified provider configuration as exclusively European hosting.',
    'Where GDPR applies, transfers need an applicable lawful mechanism, such as an adequacy decision or appropriate contractual safeguards, and any required supplementary measures. A privacy notice does not itself create those safeguards. You can request information about safeguards relevant to your data from the contact above.'
  ] },
  { title: 'Retention and deletion', paragraphs: [
    'Account records and saved application data remain until you remove the records or delete your account. The self-service deletion flow permanently removes your authentication account and its active application records, including saved settings, QR codes, wishlists, access overrides, usage records, and terms-acceptance receipts. Shared wishlists disappear with their owner’s data.',
    'New account-associated backend transfers and media jobs are cancelled and removed during self-service deletion. Legacy files created before account ownership was recorded cannot always be matched to your account: send us the relevant transfer/job link if you need help removing one. Anonymous guest wishlist reservations are associated with an item and a private cancellation capability, not with an email account; use the reservation cancellation control or contact us with the relevant link.',
    'Normal backend expiry is shown for transfers/images where available. Defaults are seven days for transfers, about one hour for image jobs, two hours of inactivity for subtitle projects, and 30 minutes for completed video-download jobs. Cleanup is periodic, so expired files may remain until the next sweep; active processing can take longer. Recognition audio is removed after processing. A minimal in-memory account-identifier tombstone is retained for roughly 24 hours after erasure, until periodic cleanup, to prevent in-flight jobs from recreating erased files.',
    'Deleting active data does not instantly purge provider backups, security/audit logs, or information that must be retained for a legal obligation or a necessary legal claim. Provider backup/log periods are not yet confirmed; we will give available details when you request them. We do not promise a deletion deadline for systems whose settings have not been verified. Data in backups must not be restored into ordinary use without respecting prior deletion requests.',
    'Support correspondence is retained only while needed to address the matter and any applicable legal obligation or claim. Browser-stored tokens, preferences, and guest capabilities remain until you remove them, clear site storage, or use the local-data clear control. Other devices and copies you downloaded are under your control.'
  ] },
  { title: 'Browser storage and tracking choices', paragraphs: [
    'Toolbox uses browser storage for the Supabase login session, selected language, sidebar preferences, temporary meal-planner preferences, and guest wishlist cancellation capabilities. These support the features you request. You can clear Toolbox preferences from your account or use your browser’s site-data settings; clearing guest capabilities can remove your ability to cancel an existing reservation.',
    'The application does not include advertising trackers or an analytics SDK. We do not use a Do Not Track or Global Privacy Control signal to enable or disable advertising because Toolbox does not conduct that advertising activity. Hosting and external providers can have their own logs or browser-storage behaviour. Any future non-essential tracking that requires consent must be introduced with an appropriate choice before activation.'
  ] },
  { title: 'Your rights and contact', paragraphs: [
    'Depending on the law that applies, you may have rights to access, correction, erasure, restriction, portability, objection, withdrawal of consent where processing relies on consent, and an appeal or complaint about a rights decision. We do not make solely automated decisions with legal or similarly significant effects; app access is managed by the operator.',
    'Use Account → Download my data for a JSON copy of your account’s stored application records, and Account → Delete my account for self-service erasure. These controls remain available even if your account is suspended or an app is restricted. Contact privacy@zacsvae.com for other requests, an inaccessible account, anonymous guest data, or data not included in the automatic export. We may ask for proportionate identity verification, without requesting your password by email.',
    'For GDPR requests we respond without undue delay and normally within one month, subject to the legally permitted extension for complex or numerous requests, which we explain. Other applicable jurisdictions may use different deadlines and exceptions. We do not discriminate against people for exercising legally protected privacy rights.',
    'You can complain to the Belgian Data Protection Authority at dataprotectionauthority.be or to a competent authority in your country. You may contact us first, but doing so is not a condition for exercising a regulatory complaint right. California, UK, Canadian, Australian, and other mandatory privacy protections apply where their legal scope is met; this notice does not limit them.'
  ] },
  { title: 'Changes', paragraphs: [
    'We publish the date/version of this notice and the Terms. Material changes to processing will be brought to users’ attention and any required new consent will be sought separately. The current notice describes the service as operated today, rather than authorizing undisclosed future uses.'
  ] }
]

export const termsSections: LegalSection[] = [
  { title: 'Operator and agreement', paragraphs: [
    'Toolbox is provided by Isaac Sauer in Belgium. Contact privacy@zacsvae.com. These Terms govern your use of toolbox.zacsvae.com and its Toolbox backend. Read the Privacy Policy for how personal data is handled. Account users must expressly agree to these Terms; merely opening the Privacy Policy is not consent to optional processing.',
    'The service is intended for adults. You must be at least 18 to create or use an account and able to enter the agreement under applicable law. We do not ask for your date of birth, but record your adult attestation. If you believe a child has created an account, contact us so we can address it.'
  ] },
  { title: 'Accounts and access levels', paragraphs: [
    'Keep your credentials secure, use an email address you control, and contact us if you suspect unauthorized use. You are responsible for activity you authorize through your account; this does not waive rights regarding unauthorized transactions or our own security obligations.',
    'Free and Pro are access levels, not paid subscriptions. Pro provides access to operator-managed backend tools under the permissions shown for your account; the operator can configure app access and saved-data limits per account type and per account. There are currently no fees, automatic renewals, or payment details collected for these plans. Any future paid service would require separate clear pricing and agreement.',
    'Saved-data limits, file sizes, processing concurrency, provider availability, and retention may affect a tool. “Unlimited saves” means no Toolbox per-app saved-data quota; it does not mean unlimited hardware, bandwidth, processing time, or third-party/project resources.'
  ] },
  { title: 'Your content and lawful use', paragraphs: [
    'You retain rights in your content. You grant the operator only the permission needed to store, process, transmit, and display it to provide the features you request, including sharing with recipients through links you enable. This is not a licence to sell your content or use private uploads for advertising or model training.',
    'Only upload, download, transform, or share content you are entitled to use. Respect copyright, privacy, provider terms, and other people’s rights. Do not use Toolbox for unlawful content, harassment, malware, unauthorized system access, credential theft, unlawful surveillance, or bypassing payment/access restrictions. Do not evade quotas or deliberately overload the backend. A video-download or media tool does not grant permission to obtain protected content.',
    'Do not upload other people’s sensitive data unless you have a lawful reason and any necessary permission. The service is not designed as a records system for medical, emergency, legal, or regulated professional work. If you share a link, review what it exposes and understand that recipients can retain their own copies.'
  ] },
  { title: 'Media downloads and rights confirmation', paragraphs: [
    'Before each server-side URL download in Video Downloader or Subtitle Studio, you must expressly confirm that you have the necessary rights or another lawful basis to download and process the requested media. Do not bypass DRM, paywalls, authentication, or other access restrictions. Check applicable copyright law and source-site rules before making the request.',
    'The confirmation applies to that download request only. It is not remembered as permission for future downloads; changing the source URL or starting another request requires a new confirmation. Account and app permissions continue to apply. Uploading your own video for subtitles does not initiate a remote URL download, but remains subject to the lawful-use requirements above.',
    'Toolbox and its use of yt-dlp do not grant copyright permission, prove that a source is lawful, or establish that a requested download is allowed. Your declaration is an attestation and a condition of using the feature, not a legal immunity or waiver of mandatory rights. You remain responsible under applicable law for your submissions and actions; the operator remains responsible for its own acts and legal obligations.',
    'If you believe a Toolbox media request infringes your rights, contact privacy@zacsvae.com. Identify the relevant work, Toolbox file/job or link if available, your basis for claiming rights, and a way to contact you. We may restrict the relevant access or remove material where appropriate after reviewing the report. This contact process does not limit any remedy available under applicable law.'
  ] },
  { title: 'Availability, accuracy, and external services', paragraphs: [
    'Toolbox is a collection of utilities provided without a charge. Features may depend on external providers, browsers, AI models, and experimental implementations. Forecasts, estimates, transcriptions, image outputs, imported prices, routing, and other results can be incomplete or inaccurate. Check results before relying on them; tools do not replace qualified professional advice where it is needed.',
    'We aim to keep the service useful and reasonably secure, but do not promise uninterrupted access, permanent file hosting, or a particular processing result. Temporary uploads expire. Keep your own copies of files and export saved data if you need a backup. External services have their own terms and availability; their rights and your mandatory legal protections remain in force.'
  ] },
  { title: 'Suspension, changes, and closing an account', paragraphs: [
    'We may restrict or suspend access where reasonably needed to address abuse, unlawful activity, a security incident, resource constraints, or a breach of these Terms. Where practical and lawful, we will explain the reason and provide a way to contact us or challenge a mistake. Access to privacy information, data export, deletion, and privacy requests remains available.',
    'You may close your account through the account page. Deletion is permanent for active account data and invalidates owner-held shared wishlists and new account-associated backend files. Recipients’ copies and provider backups/logs are subject to the Privacy Policy. Deleting the master account also removes its account-management access; other users’ accounts are not deleted.',
    'We may change features or these Terms for a reasonable service, security, or legal reason. Material changes will be identified and, where required, notified before taking effect. Continued use alone is not a replacement for a new express agreement where law requires it. If a change is unacceptable, you can export your data and close your account.'
  ] },
  { title: 'Responsibility and mandatory rights', paragraphs: [
    'We do not exclude or limit liability where doing so is unlawful, including liability that cannot be excluded for fraud, intentional wrongdoing, gross negligence, injury, or other protected matters. Applicable consumer guarantees, remedies, privacy rights, and other mandatory rights are preserved. These Terms do not impose a blanket indemnity, compulsory arbitration, or waiver of class or regulatory remedies.',
    'To the extent permitted by applicable law, the free service is provided as available without a contractual guarantee that every tool will fit a particular purpose. Each party remains responsible under applicable law for its own acts and obligations; this does not transfer the operator’s legal duties to you.'
  ] },
  { title: 'Law, disputes, and contact', paragraphs: [
    'Belgian law governs these Terms to the extent a choice of law is permitted. If you are a consumer, this choice does not deprive you of mandatory protection under the law that applies in your country of habitual residence. Courts and regulators remain available as provided by applicable law; these Terms do not require you to bring a consumer claim exclusively in Belgium.',
    'Send service questions, complaints, suspected misuse, or rights concerns to privacy@zacsvae.com. We will try to resolve concerns fairly. If any part of these Terms is unenforceable, the remaining parts continue only to the extent permitted by law.'
  ] }
]
